#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/promission?characterEncoding=utf-8
#jdbc.url=jdbc:mysql://localhost:3306/promission?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#jdbc.username=root
#jdbc.password=123456
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/promission?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&characterEncoding=utf-8
jdbc.username=root
jdbc.password=123456